/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class EventLogReader */

#ifndef _Included_EventLogReader
#define _Included_EventLogReader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     EventLogReader
 * Method:    getNumLogsProcessed
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_EventLogReader_getNumLogsProcessed
  (JNIEnv *, jobject);

/*
 * Class:     EventLogReader
 * Method:    retrieveSecurityLogs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_EventLogReader_retrieveSecurityLogs
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
